apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: ai-task-platform
spec:
  clusterIP: None
  selector:
    app: worker
  ports:
    - name: worker
      port: 8081
      targetPort: 8081
